M48
; DRILL file {KiCad 6.0.11+dfsg-1} date Sat Nov 18 19:22:08 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-18T19:22:08+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1063
%
G90
G05
T1
X2.2644Y-4.5255
X2.2644Y-4.7531
T2
X2.0748Y-4.3602
T3
X2.1358Y-4.9409
X3.8484Y-3.3465
T0
M30
